### ISSUE TITLE
BioC submission

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsBackendMgf#10]
I'm started using the `MsBackendMgf` backend already in a vignette in `xcms` that describes how LC-MS/MS data can be processed with `xcms`. In order for this vignette to run we should submit this package to Bioconductor (see also issue https://github.com/sneumann/xcms/issues/546).

@lgatto I can take care of that if you don't have time for it.

**Comment by lgatto** [comment]
Yes, please go ahead. Thanks!

**Comment by jorainer** [comment]
Submitted: https://github.com/Bioconductor/Contributions/issues/1930
