### ISSUE TITLE
sticker

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsBackendMgf#12]
Sticker for `MsBackendMgf`. I didn't find a logo or something equivalent for *mascot generic format*, thus I've just used the MGF. @lgatto do you know of any logo for MGF files? 
The sticker is the same as for `MsBackendMassbank` except of the logo and the name.

![MsBackendMgf](https://user-images.githubusercontent.com/5506112/109987132-a5363100-7d06-11eb-966e-c9f28092c234.png)

**Comment by lgatto** [comment]
I don't know of any logo. mgf stands for [Mascot Generic Format](http://www.matrixscience.com/help/data_file_help.html), and Mascot is a commercial piece of software by Matrix Science. I'm happy to leave it like this.
