### ISSUE TITLE
Unify header keys

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsBackendMgf#2]
A TODO for this backend is to harmonise the many different ways to encode the same information in mgf files. I am for a simple solution that would use a [simple key-value table](https://github.com/rformassspectrometry/MsBackendMgf/issues/1#issuecomment-580188499) such the one below:
```
| key        | value             |
|:-----------|:------------------|
|CHARGE      |precursorCharge    |
|PEPMASSMZ   |precursorMz        |
|PEPMASSINT  |precursorIntensity |
|IONMODE     |polarity           |
|MSLEVEL     |msLevel            |
|RTINSECONDS |rtime              |
|RT          |rtime              |
|SCANS       |scanIndex          |
```

I have some code that already does this and will send a PR at some point.

**Comment by jorainer** [comment]
God idea! I'd suggest that we define a default mapping for all *core* `spectraVariables`. This could be a simple character vector, names being the spectra variable for `Spectra` and value the expected field in the mgf file. For fields in the mgf for which no mapping is provided the field name could be used as column name in the `spectraData` `DataFrame`.

the default could be returned by a function like `spectraVariableKeys()` (or `spectraVariableFields()`) which could be used in the import function as a default. Users can alternatively change that or provide their own mapping.

**Comment by lgatto** [comment]
The key/values aren't 1-1, so I thought the easiest (especially for users) would be a `data.frame` - is branch `issue2`, you'll find 
```r
> mgfKeyValues()
          key              value
1      CHARGE    precursorCharge
2   PEPMASSMZ        precursorMz
3  PEPMASSINT precursorIntensity
4     IONMODE           polarity
5     MSLEVEL            msLevel
6 RTINSECONDS              rtime
7          RT              rtime
8       SCANS          scanIndex
```
That is passed by default to the constructor:

```r
setMethod("backendInitialize", signature = "MsBackendMgf",
          function(object, files, keyValues = mgfKeyValues(),
                   nonStop = FALSE, ..., BPPARAM = bpparam()) 
...
```

**Comment by lgatto** [comment]
@jorainer @michaelwitting @adelabriere - do you have any often used and of general interest key/pair values that could be added here?

**Comment by michaelwitting** [comment]
When linking MS1 and MS2 features I'm using the ID of the MS1 feature in the .mgf file. But dependent on the workflow (e.g. GNPS or something else) they are called different, since the workflows demand specific formats.
For library spectra from GNPS I would say keys like `INCHI`, `SMILES`, `INCHIKEY`, `FORMULA` would be reoccuring values.

**Comment by jorainer** [comment]
IMHO the default `mgfKeyValues` should *only* provide the mapping of MGF fields to the *core* [spectra variables](https://github.com/rformassspectrometry/Spectra/blob/master/R/MsBackendDataFrame-functions.R#L82:L101). For those that are not defined there I would *by default* just use the field name as `colname` in `Spectra`.

**Comment by lgatto** [comment]
Indeed, that also how I see it. Any non core variables will be added automatically, as they are named. I they need any special treatment, this would be delegated to a specialised backend.

The mappings I show above are the only ones I have ever encountered. If any of you is aware of any fields out there that match our core variables, please post them here and I will add them to the default key/value pairs.

**Comment by lgatto** [comment]
I think this is now addressed with the `spectraVariableMapping()` function.
