### ISSUE TITLE
Extracting a specific scan from an MGF file.

### ISSUE THREAD

**Issue by HijaziHassan** [rformassspectrometry/MsBackendMgf#29]
The aim is to get the mz and intenisty values of one scan from an mgf file.
Is there a faster way than transforming mgf file into `Spectra` object through using the `MsBackendMgf()` then to filter through `acquisitionNum` spectral variable to get the `peaksData()` of this  specific scan?

Thank you.

**Comment by lgatto** [comment]
What do you mean faster? Less code to write? Shorter execution time?

**Comment by HijaziHassan** [comment]
Mixture of both. 
In other words, is there an accessor function that access mgf file and retreives specific scan without passing through `Spectra` object.  
If not, shall I add any thing to this code: `Spectra(mgf_file, source = MsBackendMgf())` to enhance the execution time (because I saw in one of the vignette that you added `BiocParallel::register(SerialParam())` at the beginning of the code).
Thank you Laurent.

**Comment by lgatto** [comment]
To access an arbitrary scan, you must first parse the whole file. That's what `Spectra()` will do, which can take time depending on the the size of that file. Parallel processing for that first might help, depending on the number of files and the disk you have. Afterwards, accessing said scan, is fast. 

Making things faster without context doesn't make much sense.

**Comment by HijaziHassan** [comment]
Actually this why I asked to see if I'm missing something. Because `read` function from `pyteomics.mgf` module in python by default reads MGF file as IndexedMGF instance. This is much faster to achieve what I'm aiming at.

**Comment by lgatto** [comment]
I've never used any indexed mgf files. mzML are, always (I believe).

If you know the index of the single scan you want to read, it wouldn't be too difficult to write a function that specifically returns the (intensity,mz) pairs. You would need to could the `BEGIN IONS` lines and, if you want the scan `i`, extract the lines between the i's and (i+1)'s lines. See the functions in `functions-mgf.R` for details.
