### ISSUE TITLE
Support non-standard fields

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsBackendMgf#3]
There is a need for greater flexibility and make sure we [support non-standard fields](https://github.com/rformassspectrometry/MsBackendMgf/issues/1#issuecomment-614824258). 

Please discuss these needs here.

**Comment by jorainer** [comment]
I would just add values from additional fields present in the mgf as additional columns to the `spectraData` `DataFrame`. Same for the export, additional columns in the `spectraData` get exported to the mgf file using the column name in the `spectraData` as field name.

**Comment by michaelwitting** [comment]
I agree with @jorainer . Should be the easiest solution. I'm currently planing the same things for the MassBank records: Everything that is not supported by the `Spectra` object goes to additional columns.

**Comment by lgatto** [comment]
The point that I think is worth discussing is how flexible we want to be. Supporting new fields is important, and this is actually already working in branch `issue2`:
```r
> sp <- Spectra("spectratest.mgf", source = MsBackendMgf())
Start data import from 1 files ... done
> sp$FOO
[1] "1" "1" "1"
```
But what is currently failing to to read spectra (from files) with different headers. For example the following
```
BEGIN IONS
TITLE=File193 Spectrum1968 scans: 2432
PEPMASS=780.83954 1265631.00000
FOO=1
CHARGE=2+
RTINSECONDS=1127
SCANS=2432
102.05556 1340.44
1335.64368 1532.12
END IONS

BEGIN IONS
TITLE=File193 Spectrum1968 scans: 2432
PEPMASS=780.83954 1265631.00000
CHARGE=2+
RTINSECONDS=1127
SCANS=2432
102.05556 1340.44
1335.64368 1532.12
END IONS
```
would fail because `FOO` is present in only one spectrum. I would expect such cases to be the exception, and arguably slightly pathological. 

Should the backend support such cases?

**Comment by jorainer** [comment]
If you have a function that handles each spectrum separately, i.e. takes the infos from *BEGIN IONS* to *END IONS* and returns a `data.frame` or `DataFrame` with the information and hence you get a `list` of such `data.frame`s, one per spectrum, you could use the `MsCoreUtils::rbindFill` function to join these and automatically handle these cases. In your example you would get a `data.frame` with a column `"FOO"` that has a value `1` for the first and `NA` for the second spectrum.

**Comment by lgatto** [comment]
Thanks @jorainer - my question was rather whether we want to do this, not whether we can do it. From you answer, I gather than it's a yes. :-)

**Comment by jorainer** [comment]
I depends :) I just wanted to highlight a way how it could be done - without saying that I think it's ideal, because having x `data.frame`s and `rbind`ing them might not be the most efficient thing to do. So, if you found a better, more efficient and elegant way to do it I wouldn't mind if we would **not** support such cases.

**Comment by lgatto** [comment]
Yes, the more *features* and flexibility we want to support, the more we will pay in terms of maintainability and speed. I will try to do some benchmarks.
