### ISSUE TITLE
could not find function "asDataFrame<-"

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsBackendMgf#6]
When running line 61 in the vignette:

```r
> sps <- Spectra(fls, source = MsBackendMgf())
Start data import from 2 files ... done
Error in asDataFrame(object) <- res : 
  could not find function "asDataFrame<-"
```

Ping @jorainer

**Comment by jorainer** [comment]
Yepp - I would provide a PR to fix that once the `Spectra` submission is over. The `export` functionality is not yet in `Spectra`.

**Comment by lgatto** [comment]
Sorry, I thought the PR was complete.
